# -*- coding: utf-8 -*-
"""TesseractOCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dzc6bS57Q1EEtSmrgwOTZEruOEWM1nXe
"""

# !sudo apt install tesseract-ocr
# !sudo apt install tesseract-ocr-script-hang tesseract-ocr-script-hang-vert
# !pip install pytesseract

import pytesseract
import cv2
import os
from PIL import Image

class_names = ['건강보험료납부확인서', '근로소득원천징수', '자동차등록증',
               '자동차등록원부', '자격득실확인서', '자동차매매계약서', '소득금액증명서']

def getData(url, imgType):
    toSend = dict()
    toSend['file_name'] = imgType
    img = cv2.imread(url)
    if imgType == '자격득실확인서':
        
        x, y = 786, 362
        w, h = 80, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        birth = f'{res[:2]}.{res[2:4]}.{res[4:6]}'
        toSend['생년월일'] = birth
        x, y = 328, 556
        w, h = 200, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1]

        comp_name = arr
        toSend['회사명'] =  comp_name[0]

        x, y = 826, 556
        w, h = 250, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        startDate = res.split('\n')[0:-1][0]
        toSend['자격취득일'] = startDate
        print(toSend)

    elif imgType == '건강보험료납부확인서':

        x, y = 948, 290
        w, h = 170, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        toSend['생년월일'] = res.split('\n')[0:-1][0]

        x, y = 400, 340
        w, h = 180, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1]
        toSend['회사명'] =  arr
        

        
        x, y = 270, 539
        w, h = 170, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        toSend['연봉'] = str(int(int(res.split()[0])*291.54))+'원'
        print(toSend)

    elif imgType == '소득금액증명서':
        
        x, y = 170, 388
        w, h = 300, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        loc = ' '.join(res.split()[:2])
        toSend['주소'] = loc

        x, y = 302, 638
        w, h = 180, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1][0]
        toSend['회사명'] =  arr
        
        x, y = 680, 665
        w, h = 200, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1][0]
        toSend['연봉'] =  str(int(arr)*12)+'원'
        
        x, y = 170, 1252
        w, h = 250, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        phone = res.split('\n')[0:-1][0]
        toSend['전화번호'] = phone

    elif imgType == '근로소득원천징수':

        x, y = 919, 325
        w, h = 100, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1]
        toSend['대표자명'] = arr

        x, y = 409, 325
        w, h = 180, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1][0]
        toSend['회사명'] =  arr
        
        x, y = 1053, 463
        w, h = 200, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1][0]
        toSend['주민등록번호'] =  arr

        
        x, y = 409, 363
        w, h = 220, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = ''.join(res.split('\n')[0:-1])
        arr = arr[:3]+'-'+arr[4:]
        toSend['사업자등록번호'] =  arr


        x, y = 1005, 397
        w, h = 100, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1][0]
        toSend['종사업장일련번호'] =  arr

        
        x, y = 421, 714
        w, h = 200, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1][0]
        toSend['연봉'] =  str(int(arr)*12)+'원'
    
    elif imgType == '자동차매매계약서':
        x, y = 838, 219
        w, h = 150, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1][0]
        toSend['접수일자'] = arr

        x, y = 390, 670
        w, h = 150, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1][0]
        toSend['차대번호'] = arr

        x, y = 1060, 455
        w, h = 70, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        birth = f'{res[:2]}.{res[2:4]}.{res[4:6]}'
        toSend['생년월일'] = birth

        x, y = 387, 505
        w, h = 200, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        phone = res.split('\n')[0:-1][0]
        toSend['전화번호'] = phone

        x, y = 1041, 621
        w, h = 90, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='eng+kor')
        carType = res.split('\n')[0:-1][0]
        toSend['차종'] = carType

        x, y = 395, 721
        w, h = 130, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        carPrice = res.split('\n')[0:-1][0]
        toSend['가격'] = carPrice
    print(toSend)
    return(toSend) 

if __name__ == '__main__':
    # getData('.//data//자격득실확인서1.png', '자격득실확인서')
    # getData('.//data//건강보험료납부확인서1.png', '건강보험료납부확인서')
    # getData('.//data//소득금액증명서1.png', '소득금액증명서')
    # getData('.//data//자동차매매계약서1.png', '자동차매매계약서')
    # getData('.//data//근로소득원천징수영수증1.png', '근로소득원천징수')
    getData('.//data//자동차등록증1.png', '자동차등록증')