JWT_SECRET = "ABCD1234!"
JWT_ALGORITHM = "HS256"

AWS_ACCESS_KEY_ID="AKIAQZZYQFHCCPMKEQM6"
AWS_SECRET_ACCESS_KEY="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"
AWS_REGION = 'ap-northeast-2'
S3_Bucket = "ssafy-project2"